serviceAccount:
  create: true
  name: aws-for-fluent-bit
  annotations: {}

cloudWatch:
  enabled: true
  region: ""                 # set by install script
  autoCreateGroup: true
  logStreamPrefix: "fb-"
  logGroupTemplate: ""       # set by install script: /aws/eks/<cluster>/$(namespace)
  logGroupName: ""           # unused when template is set
