apiVersion: v1
kind: Namespace
metadata:
  name: demo-velero
  labels:
    app.kubernetes.io/part-of: rsedp
    app.kubernetes.io/name: demo-velero
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-velero
  namespace: demo-velero
  labels:
    app: demo-velero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-velero
  template:
    metadata:
      labels:
        app: demo-velero
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo:1.0.0
          args:
            - "-listen=:5678"
            - "-text=ok"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: demo-velero
  namespace: demo-velero
spec:
  selector:
    app: demo-velero
  ports:
    - name: http
      port: 5678
      targetPort: 5678
